[package]
name = "rust-raytracer"
version = "0.1.0"
authors = [
    "ng.guoyou@gmail.com",
    "stacey.ell@gmail.com"
]

[dependencies]
image = "*"
num = "*"
num_cpus = "*"
rand = "*"
rustc-serialize = "*"
threadpool = "*"
time = "*"
